### ISSUE TITLE
States

### ISSUE THREAD

**Issue by phemmylintry** [obidient/23ForObiApi#9]
States are provided by [bigfastapi](https://bigfa.st/docs/countries/get_country_states_countries__country_code__states_get). 
Import the states module

Example
```python
from bigfastapi.countries import app as countries

app.include_router(countries, tags=["Countries"])
```

## Task

- [ ] Get all states
- [ ] get state details

**Comment by mikenrowland** [comment]
@phemmylintry assign this to me

**Comment by mikenrowland** [comment]
Hi boss @phemmylintry I've been trying to wrap my head round this issue. So after my setup and importing countries from bigFast, I can't seem to understand what else this endpoint should be doing since BigFastAPI already returns a list of all states @ this url http://127.0.0.1:7001/countries/NGA/states

**Comment by phemmylintry** [comment]
@mykie88 For state details, please create a model to store extra state details such as
* current state governor
* state capital
and other info you deem necessary, then create a get API for it. Thanks

**Comment by phemmylintry** [comment]
This has been implemented
